// TAROTLENS — données produits
window.PRODUCTS = [
    // ── DECKS ──
    { id: 1, name: "Has Been Tarot",      tag: "Tarot",      cat: "deck",      cards: 87, format: "Poker 63×89mm",      weight: "310g finition Soft Touch", delivery: "Jeu livré dans pochon, accompagné de ces goodies",                  price: 49, badge: "new", glyph: "✺", grad: "g-hasbeen",  img: "images/hasbeen-card.jpg" },
    { id: 2, name: "Too Much Lenormand",  tag: "Lenormand",  cat: "deck",      cards: 46, format: "Poker 65×89mm",      weight: "310g finition Soft Touch", delivery: "Jeu livré dans pochon, accompagné de ces goodies",                  price: 49, badge: "new", glyph: "❉", grad: "g-lenormand", img: "images/lenormand-card.jpg" },
    { id: 3, name: "Too Much Tarot",      tag: "Tarot",      cat: "deck",      cards: 82, format: "Standard 70×120mm",  weight: "350g finition Soft Touch", delivery: "Jeu livré dans un bandana ou pochon, accompagné de ces goodies",    price: 49, badge: null,  glyph: "✶", grad: "g-toomuch",   img: "images/toomuch-card.jpg" },
    { id: 4, name: "Bundle",              tag: "Bundle",     cat: "bundle",    cards: null, format: null,               weight: null,                       delivery: "L'ensemble des 3 decks TarotLens",                                 price: 49, badge: null,  glyph: "✦", grad: "g-bundle",    img: null },
    // ── ACCESSOIRES ──
    { id: 5, name: "Bougie Martini",      tag: "Accessoire", cat: "accessory", cards: null, format: null,               weight: null,                       delivery: null,                                                               price: 49, badge: null,  glyph: "✿", grad: "g-acc1",      img: "images/Bougies/bougie-martini.jpg" },
    { id: 6, name: "Bougie Matcha Latte", tag: "Accessoire", cat: "accessory", cards: null, format: null,               weight: null,                       delivery: null,                                                               price: 49, badge: null,  glyph: "✿", grad: "g-acc2",      img: "images/Bougies/bougie-matcha.jpg" },
    { id: 7, name: "Bougie Ube Latte",    tag: "Accessoire", cat: "accessory", cards: null, format: null,               weight: null,                       delivery: null,                                                               price: 49, badge: null,  glyph: "✿", grad: "g-acc3",      img: "images/Bougies/bougie-ube.jpg" },
    { id: 8, name: "Bougie Tomate",       tag: "Accessoire", cat: "accessory", cards: null, format: null,               weight: null,                       delivery: null,                                                               price: 49, badge: null,  glyph: "✿", grad: "g-acc4",      img: "images/Bougies/bougie-tomate.jpg" },
    { id: 9, name: "Bougie Orange",       tag: "Accessoire", cat: "accessory", cards: null, format: null,               weight: null,                       delivery: null,                                                               price: 49, badge: null,  glyph: "✿", grad: "g-acc5",      img: "images/Bougies/bougie-orange.jpg" },
    { id: 10, name: "Bougie Citron",      tag: "Accessoire", cat: "accessory", cards: null, format: null,               weight: null,                       delivery: null,                                                               price: 49, badge: null,  glyph: "✿", grad: "g-acc6",      img: "images/Bougies/bougie-citron.jpg" },
    { id: 11, name: "Bougie Fraise",      tag: "Accessoire", cat: "accessory", cards: null, format: null,               weight: null,                       delivery: null,                                                               price: 49, badge: null,  glyph: "✿", grad: "g-acc7",      img: "images/Bougies/bougie-fraise.jpg" },
];
